# -*- coding: utf-8 -*-
"""summarize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uZopvkt9og_E7NunPqhB_rYt0e8haual
"""

# Install required packages
# pip install transformers gradio

from transformers.pipelines import PIPELINE_REGISTRY
from transformers import pipeline

# Getting the list of supported tasks
print(PIPELINE_REGISTRY.get_supported_tasks())

# Loading the BART model for text summarization
summarizer_bart = pipeline("summarization", model="facebook/bart-large-cnn")

# Sample paragraph for testing
test_paragraph = """
Bulletproof Boy Scouts, also known as the Bangtan Boys, is a South Korean boy band formed in 2010. The band consists of Jin, Suga, J-Hope, RM, Jimin, V, and Jungkook, who co-write or co-produce much of their material. Originally a hip hop group, they expanded their musical style to incorporate a wide range of genres, while their lyrics have focused on subjects including mental health, the troubles of school-age youth and coming of age, loss, the journey towards self-love, individualism, and the consequences of fame and recognition. Their discography and adjacent work has also referenced literature, philosophy and psychology, and includes an alternate universe storyline.
"""

# Summarizing the paragraph using the BART model
summary_bart = summarizer_bart(test_paragraph, max_length=100, min_length=40, do_sample=False)
print("BART Model Summary:", summary_bart[0]['summary_text'])